libzzip = {
    'files': [
        'dir.c',
        'err.c',
        'fetch.c',
        'file.c',
        'fseeko.c',
        'info.c',
        'memdisk.c',
        'mmapped.c',
        'plugin.c',
        'stat.c',
        'write.c',
        'zip.c',
    ],

    'dependencies': [
        'zlib',
    ],

    'environment': {
        'CPPPATH': ['source/zlib', 'source'],
    },
}

Return('libzzip')
